theme: jekyll-theme-slate
title: Open Referral UK Data Standard
url: https://porismjamesdavidson.github.io/

markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-relative-links

exclude:
  - .idea/
